version: '3'

includes:

  box:
    taskfile: ./Taskfile.box.yaml
    optional: true

tasks:

  packages:
    desc: Interactively build distribution packages
    interactive: true
    cmds:
      - ./build-packages.sh

  clean:
    desc: Clean the build environment
    cmds:
      - rm -rf ./build
