set(PACKAGE_VERSION "@USDR_VERSION@")

if(PACKAGE_VERSION AND PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
    set(PACKAGE_VERSION_COMPAT FALSE)
else()
    set(PACKAGE_VERSION_COMPAT TRUE)
endif()

if(NOT PACKAGE_VERSION_COMPAT)
    message(FATAL_ERROR "The installed usdr version (${PACKAGE_VERSION}) does not satisfy requested version ${PACKAGE_FIND_VERSION}.")
endif()
