# Ubuntu Bionic Beaver (18.04)
FROM ubuntu:18.04

ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install build-essential curl gcc-8 g++-8 -y
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 80 \
    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 80 \
    && update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-8 80 \
    && update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-8 80

# Install fresh version of Cmake
RUN apt-get install libssl-dev -y
RUN cd /tmp \
    && curl -fsSL https://github.com/Kitware/CMake/releases/download/v3.28.3/cmake-3.28.3.tar.gz -o cmake-3.28.3.tar.gz \
    && tar xzf cmake-3.28.3.tar.gz \
    && cd cmake-3.28.3 \
    && ./bootstrap \
    && make \
    && make install \
    && cd .. \
    && rm -rf cmake-3.28.3 cmake-3.28.3.tar.gz \
    && update-alternatives --install /usr/bin/cmake cmake /usr/local/bin/cmake 10

RUN apt-get install python3.8 python3.8-distutils -y
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 10
RUN curl -fsSL https://bootstrap.pypa.io/pip/3.8/get-pip.py | python3.8
RUN python3.8 -m pip install pyyaml

RUN apt-get install dwarves libusb-1.0-0-dev libsoapysdr-dev check -y
RUN apt-get install dh-make devscripts debhelper dkms -y

ARG TARGETARCH
ARG TASK_VERSION=3.53.1
RUN curl -fsSL "https://github.com/go-task/task/releases/download/v${TASK_VERSION}/task_linux_${TARGETARCH}.tar.gz" \
    | tar -xz -C /usr/local/bin task

RUN mkdir -p /work/build
RUN mkdir -p /work/source
RUN mkdir -p /work/output
ENV PACKAGE_DIR_NAME=ubuntu-bionic
ENV PACKAGE_ARCH_NAME=unknown
WORKDIR /work/

CMD ["tail", "-f", "/dev/null"]
