version: '3'

tasks:

  clean:
    desc: Clean the build environment
    cmds:
      - rm -rf /work/build
      - rm -rf /work/output/*
      - mkdir -p /work/build

  deb:
    desc: Build the debian packages
    internal: true
    deps:
      - clean
    dir: /work/build/source
    cmds:
      - cp -ra /work/source /work/build/
      - ln -s packaging/{{.FOLDER}} debian
      - debuild -us -uc -eDH_VERBOSE=1
      - cp -ra /work/build/*.deb /work/output/

  deb-ubuntu:
    desc: Build the debian packages for Ubuntu
    cmds:
      - task: deb
        vars:
          FOLDER: ubuntu

  deb-ubuntu-bionic:
    desc: Build the debian packages for Ubuntu Bionic(18.04)
    cmds:
      - task: deb
        vars:
          FOLDER: ubuntu-bionic

  deb-debian-bookworm:
    desc: Build the debian packages for Debian Bookworm(12)
    cmds:
      - task: deb
        vars:
          FOLDER: debian-bookworm

  ppa:
    desc: Upload the debian package to the ppa
    deps:
      - clean
    preconditions:
      - test -d /mnt/gnupg
      - test -d debian/
    dir: /work/build/source
    cmds:
      - rm -rf /root/.gnupg
      - cp -ra /mnt/gnupg /root/.gnupg 2>/dev/null | true
      - rm -rf /root/.gnupg/S.* /root/.gnupg/public-keys.d/.* /root/.gnupg/public-keys.d/*.lock
      - gpg-agent --daemon
      - debuild -S
      - dput ppa:wavelet-lab/usdr-lib /work/build/*.changes
